[package]
name = "fst-macros"
version = "0.1.0"
edition = "2021"
rust-version.workspace = true

[lib]
proc-macro = true

[dependencies]
darling = "0.14"
syn = { version = "1.0" }
quote = "1.0"
proc-macro2 = "1.0"
